// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlShorter.Data;

#nullable disable

namespace UrlShorter.Migrations
{
    [DbContext(typeof(URLShortContext))]
    [Migration("20231029153653_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("UrlShorter.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Trabajo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Diversion"
                        });
                });

            modelBuilder.Entity("UrlShorter.entities.URL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URLLong")
                        .HasColumnType("TEXT");

                    b.Property<string>("URLShort")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("URLs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdCategoria = 1,
                            URLLong = "Lasoadsat",
                            URLShort = "jef"
                        },
                        new
                        {
                            Id = 2,
                            IdCategoria = 2,
                            URLLong = "Lasotsdasdsa",
                            URLShort = "Karenaaa"
                        },
                        new
                        {
                            Id = 3,
                            IdCategoria = 2,
                            URLLong = "Ldsadsadasdasot",
                            URLShort = "asddsadsa"
                        });
                });

            modelBuilder.Entity("UrlShorter.entities.URL", b =>
                {
                    b.HasOne("UrlShorter.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
